CREATE TABLE JobOffers (
	JOID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	JOGID uniqueidentifier NOT NULL,
    JORGID uniqueidentifier NOT NULL,
	JOTitle nvarchar(255) NOT NULL,
	JOCompanyName nvarchar(255) NOT NULL,
	JOLocationType int NOT NULL,
	JOOfficeLocation nvarchar(100) NULL,
	JOEmploymentType int NOT NULL,
	JOExpirenceLevel int NOT NULL,
    JOExpirenceYears decimal NOT NULL,
	JOCategory int NOT NULL,
	JOsalaryMin decimal NOT NULL,
	JOSalaryMax decimal NOT NULL,
	JOCurrency nvarchar(50) NOT NULL,
	JOSalaryType int NOT NULL,
	JODescription nvarchar(2000) NOT NULL,
	JORequirements nvarchar(2000) NOT NULL,
	JOBenefits nvarchar(2000) NOT NULL,
	JOCreatedAt datetime2 NOT NULL,
	JOPostedAt datetime2 NOT NULL,
	JOExpiresAt datetime2 NOT NULL,
	JOStatus int NOT NULL,
)